spring:
  application:
    name: game-initializer

management:
  endpoints:
    web:
      exposure:
        include: health,env,info  # ??????????? ?????? ?????? ?????????
  endpoint:
    health:
      show-details: always  # ?????????? ????????? ?????????? ? ????????? ??????? ?? /actuator/health

info:
  java:
    enabled: true
  build:
    enabled: true
  env:
    enabled: true
